// Lista oficial de códigos de error.
// Iremos agregando más cuando los necesitemos, no antes.
export const ERROR_CODES = Object.freeze({
  RUTA_NO_ENCONTRADA: 'RUTA_NO_ENCONTRADA',
  JSON_INVALIDO: 'JSON_INVALIDO',
  VALIDACION_DATOS_INVALIDOS: 'VALIDACION_DATOS_INVALIDOS',
  SECURITY_BODY_DEMASIADO_GRANDE: 'SECURITY_BODY_DEMASIADO_GRANDE',
  RATE_LIMIT_EXCEDIDO: 'RATE_LIMIT_EXCEDIDO',
  ERROR_INTERNO: 'ERROR_INTERNO',
});